services:
  ip:
    build:
      context: .
      dockerfile: ImageProcessing/Containerfile
      args:
        BASE_IMAGE: nvcr.io/nvidia/pytorch:25.05-py3-igpu
        INSTALL_TORCH: "0"
    runtime: /usr/bin/nvidia-container-runtime
    group_add:
      - keep-groups
    devices:
      - /dev/video0:/dev/video0
    privileged: false
    security_opt:
      - label=disable
    ipc: host
