FROM docker.io/ollama/ollama:latest

ARG OLLAMA_MODEL
ARG OLLAMA_PORT

ENV OLLAMA_MODEL=${OLLAMA_MODEL}
ENV OLLAMA_HOST=0.0.0.0:${OLLAMA_PORT}

RUN ollama serve & \
    PID=$!; \
    sleep 10 && \
    ollama pull ${OLLAMA_MODEL}; \
    kill $PID 2>/dev/null || true

EXPOSE ${OLLAMA_PORT}

CMD ["serve"]
