FROM docker.io/python:3.11-slim

WORKDIR /app

COPY ArtificialIntelligence/requirements.txt ./ArtificialIntelligence/requirements.txt
RUN pip install --no-cache-dir -r ArtificialIntelligence/requirements.txt

COPY shared/ ./shared/
COPY ArtificialIntelligence/ ./ArtificialIntelligence/

ARG WITCH_AI_PORT
ARG WITCH_AI_UI_PORT
EXPOSE ${WITCH_AI_PORT}
EXPOSE ${WITCH_AI_UI_PORT}

CMD ["python", "-m", "ArtificialIntelligence.main"]
